version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MONGO_USERNAME: root
      MONGO_PASSWORD: password
      MONGO_HOST: mongo
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - flask-test-mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      
volumes:
  flask-test-mongodb: